client_id: 3MVG9fMtCkV6eLhfZXs7osmaVooWBtdfwBN17pgcDl7yaM2WmugkP4mtXSUvRL2kii9vJIsNFnzu2MnzY69rY
client_secret: 2888345369400373946
# sobject_module: SFDC_Models
username: pmmenzel@gmail.com
password: theman22sNrKCXWvjkZrxqeChuz9XQPKs
debugging: false