# client_id: ENV["SF_CLIENT_ID"]
# client_secret: ENV["SF_SECRET"]
# username: ENV["SF_USERNAME"]
# password: ENV["SF_PASSWORD"]
# debugging: false

client_id: 3MVG9fMtCkV6eLhfZXs7osmaVooWBtdfwBN17pgcDl7yaM2WmugkP4mtXSUvRL2kii9vJIsNFnzu2MnzY69rY
client_secret: 2888345369400373946
username: pmmenzel@gmail.com
password: theman22sNrKCXWvjkZrxqeChuz9XQPKs
debugging: false